<?php
function getMess() {
   $mess = array(
	   'lang' =>'zh-CN',
	   'sitename' =>'LSDB',
	   'sitedesc' =>'Local Search Data Bank',
	   'unauth_user' =>'未授权用户',
	   'page_format' =>'第%1%页',
	   'favi' =>'收藏',
	   'myfavi' =>'我的收藏',
	   'install'=>'升级',
	   'process_file'=>'档案更新',
	   'append_mode'=>'增量模式',
	   'start'=>'开始',
	   'running'=>'运行中...',
	   'update'=>'更新',
	   'updating'=>'更新中...',
	   'open'=>'打开',
	   'abort'=>'取消',
	   'speedtest'=>'测速',
	   'speed_test'=>'网速测试',
	   'tools'=>'工具',
	   'shutdown'=>'关机',
	   'restart'=>'重启',
	   'history'=>'历史',
	   'search' =>'搜索',
	   'searching' =>'正在搜索...',
	   'total_mess'=>'共 %1% 条记录, %2% 页',
	   'search_for'=>'搜索关键词',
	   'time_cost'=>'用时',
	   'prev'=>'上一页',
	   'next'=>'下一页',
	   'not_found'=>'资源未找到',
	   'all'=>'全部',
	   'default'=>'默认',
	   'date'=>'日期',
	   'create_date_asc'=>'创建日期',
	   'modify_date'=>'修改时间',
	   'multi_col'=>'多列',
	   'single_col'=>'单列',
	   'list_col'=>'列表'
   );
   return $mess;
}
?>