<?php
function getMess() {
   $mess = array(
	   'lang' =>'en',
	   'sitename' =>'LSDB',
	   'sitedesc' =>'Local Search Data Bank',
	   'unauth_user' =>'Unauthorized User',
	   'page_format' =>'Page %1%',
	   'favi' =>'Favorite',
	   'myfavi' =>'My Favorite',
	   'install'=>'Install',
	   'process_file'=>'Processing files',
	   'append_mode'=>'Append mode',
	   'start'=>'Start',
	   'running'=>'Running...',
	   'update'=>'Update',
	   'updating'=>'Updating...',
	   'open'=>'Open',
	   'abort'=>'Abort',
	   'speedtest'=>'Speedtest',
	   'speed_test'=>'Speed testing',
	   'tools'=>'Tools',
	   'shutdown'=>'Shutdown',
	   'restart'=>'Restart',
	   'history'=>'History',
	   'search' =>'Search',
	   'searching' =>'Search...',
	   'total_mess'=>'Total %1% record(s), %2% page(s)',
	   'search_for'=>'Search for',
	   'time_cost'=>'Time Cost',
	   'prev'=>'Prev',
	   'next'=>'Next',
	   'not_found'=>'Resources not found',
	   'all'=>'All',
	   'default'=>'Default',
	   'date'=>'Date',
	   'create_date_asc'=>'Created Date',
	   'modify_date'=>'Modified Date',
	   'multi_col'=>'Multiple',
	   'single_col'=>'Single',
	   'list_col'=>'List'
   );
   return $mess;
}
?>